/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crabshot.management.system.gui;

import crabshot.management.system.DBA.DBManager;
import java.awt.event.KeyEvent;

/**
 *
 * @author Shahzeb Shah
 */
public class Login2 extends javax.swing.JFrame {

    /**
     * Creates new form LoginTest2
     */
    public Login2() {
        initComponents();
        setBounds(0, 0, 1315, 735);
        this.statuslbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        userIcon2 = new javax.swing.JLabel();
        userIcon1 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        statuslbl = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        LoginMenuBG = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        username.setBackground(new java.awt.Color(217, 217, 217));
        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameKeyReleased(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(530, 280, 270, 40);

        password.setBackground(new java.awt.Color(217, 217, 217));
        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(530, 330, 270, 40);

        userIcon2.setFont(new java.awt.Font("Dotum", 1, 36)); // NOI18N
        userIcon2.setForeground(new java.awt.Color(51, 51, 51));
        userIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crabshot/management/system/Images/user icon.jpg"))); // NOI18N
        getContentPane().add(userIcon2);
        userIcon2.setBounds(488, 280, 44, 40);

        userIcon1.setFont(new java.awt.Font("Dotum", 1, 36)); // NOI18N
        userIcon1.setForeground(new java.awt.Color(51, 51, 51));
        userIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crabshot/management/system/Images/lock icon.jpg"))); // NOI18N
        getContentPane().add(userIcon1);
        userIcon1.setBounds(488, 330, 44, 40);

        loginButton.setBackground(new java.awt.Color(153, 153, 255));
        loginButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(51, 51, 51));
        loginButton.setText("SUBMIT");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(490, 400, 310, 40);

        statuslbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        statuslbl.setForeground(new java.awt.Color(255, 0, 0));
        statuslbl.setText("Incorrect! username or password is wrong..!");
        getContentPane().add(statuslbl);
        statuslbl.setBounds(490, 380, 310, 17);

        loginLabel.setFont(new java.awt.Font("Dotum", 1, 36)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(51, 51, 51));
        loginLabel.setText("LOGIN");
        getContentPane().add(loginLabel);
        loginLabel.setBounds(580, 230, 170, 40);

        LoginMenuBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crabshot/management/system/Images/login box.png"))); // NOI18N
        getContentPane().add(LoginMenuBG);
        LoginMenuBG.setBounds(450, 70, 390, 470);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crabshot/management/system/Images/login background_2.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1440, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameKeyPressed

    private void usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginButton.doClick();
        }
    }//GEN-LAST:event_usernameKeyReleased

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginButton.doClick();
        }
    }//GEN-LAST:event_passwordKeyReleased

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here
        String userName=this.username.getText();
        String userPassword=this.password.getText();
        boolean login=DBManager.login(userName, userPassword);
        if(login==true){
            MainMenu main=new MainMenu();
            main.setVisible(true);
            this.dispose();
        }
        else{
            this.statuslbl.setVisible(true);
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginMenuBG;
    private javax.swing.JLabel background;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel statuslbl;
    private javax.swing.JLabel userIcon1;
    private javax.swing.JLabel userIcon2;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
