/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crabshot.management.system.gui;

import crabshot.management.system.DBA.DBManager;
import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shahzeb Shah
 */
public class ProductsUpdate extends javax.swing.JFrame {

    /**
     * Creates new form ProductsUpdate
     */
    String name="";
    int startCount = 0;
    public ProductsUpdate() {
        initComponents();
        setBounds(0, 0, 1315, 735);
        name=Products.proName;
        showRecord(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        costField = new javax.swing.JTextField();
        costLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        unitOptions = new javax.swing.JComboBox();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        designeddeveloped = new javax.swing.JLabel();
        mainmenubox = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crabshot/management/system/Images/logo.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(550, 70, 220, 90);

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(51, 51, 51));
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(1060, 140, 200, 40);

        exitButton.setBackground(new java.awt.Color(204, 204, 204));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(51, 51, 51));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(1060, 90, 200, 40);

        logoutbutton.setBackground(new java.awt.Color(204, 204, 204));
        logoutbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logoutbutton.setForeground(new java.awt.Color(51, 51, 51));
        logoutbutton.setText("LOG OUT");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbutton);
        logoutbutton.setBounds(1060, 40, 200, 40);

        jLabel1.setFont(new java.awt.Font("Dotum", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("UPDATE PRODUCT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 190, 400, 40);

        unitLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        unitLabel.setForeground(new java.awt.Color(51, 51, 51));
        unitLabel.setText("UNIT:");
        getContentPane().add(unitLabel);
        unitLabel.setBounds(450, 460, 80, 40);

        costField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(costField);
        costField.setBounds(550, 310, 330, 40);

        costLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        costLabel.setForeground(new java.awt.Color(51, 51, 51));
        costLabel.setText("COST:");
        getContentPane().add(costLabel);
        costLabel.setBounds(454, 310, 80, 40);

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(51, 51, 51));
        nameLabel.setText("NAME:");
        getContentPane().add(nameLabel);
        nameLabel.setBounds(450, 260, 80, 40);

        priceLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(51, 51, 51));
        priceLabel.setText("PRICE:");
        getContentPane().add(priceLabel);
        priceLabel.setBounds(450, 360, 90, 40);

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(51, 51, 51));
        addressLabel.setText("QUANTITY:");
        getContentPane().add(addressLabel);
        addressLabel.setBounds(390, 410, 140, 40);

        quantityField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(quantityField);
        quantityField.setBounds(550, 410, 330, 40);

        priceField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(priceField);
        priceField.setBounds(550, 360, 330, 40);

        nameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(nameField);
        nameField.setBounds(550, 260, 330, 40);

        unitOptions.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kg", "gram", "pcs" }));
        unitOptions.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                unitOptionsPropertyChange(evt);
            }
        });
        getContentPane().add(unitOptions);
        unitOptions.setBounds(550, 460, 330, 40);

        submitButton.setBackground(new java.awt.Color(153, 153, 255));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitButton.setText("UPDATE");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton);
        submitButton.setBounds(550, 540, 130, 40);

        cancelButton.setBackground(new java.awt.Color(153, 153, 255));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(690, 540, 130, 40);

        designeddeveloped.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        designeddeveloped.setForeground(new java.awt.Color(51, 51, 51));
        designeddeveloped.setText("designed and developed by LogicsEase.com");
        getContentPane().add(designeddeveloped);
        designeddeveloped.setBounds(450, 660, 420, 40);

        mainmenubox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crabshot/management/system/Images/menu bg.png"))); // NOI18N
        getContentPane().add(mainmenubox);
        mainmenubox.setBounds(10, 10, 1320, 660);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crabshot/management/system/Images/login background_2.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1440, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new Products().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
        Login login=new Login();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        new Products().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        String name=this.nameField.getText();
        String cost=this.costField.getText();
        String price=this.priceField.getText();
        String quantity=this.quantityField.getText();
        String unit = this.unitOptions.getSelectedItem().toString();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter name");
        }
        else if(cost.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter cost of Product");
        }
        else if(price.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter price of Product");
        }
        else if(quantity.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter quantity of Product");
        }
        else if(unit.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter unit of Product");
        }
        else{
           // System.out.println("hello - else");
            int id=DBManager.getProductId(name);
            //System.out.println("id is : "+id);
            if(price.matches("[0-9]+([.][0-9]+)*") && quantity.matches("[0-9]+([.][0-9]+)*") && cost.matches("[0-9]+([.][0-9]+)*")){
                Double proCost=Double.parseDouble(this.costField.getText());
                Double proPrice=Double.parseDouble(this.priceField.getText());
                Double proQuantity=Double.parseDouble(this.quantityField.getText());
                if(unit.equals("kg")) {
                    proQuantity *= 1000;
                }
                boolean status=DBManager.updateProduct(name, proCost, proPrice, proQuantity,unit, id);
                if(status==true){
                    Products product=new Products();
                    product.setVisible(true);
                    setVisible(false);
                }
            }
            else if(!cost.matches("[0-9]+([.][0-9]+)*")){
                JOptionPane.showMessageDialog(null, "Please enter a valid number in Cost Field");
            }
            else if(!price.matches("[0-9]+([.][0-9]+)*")){
                JOptionPane.showMessageDialog(null, "Please enter a valid number in Price Field");
            }
            else if(!quantity.matches("[0-9]+([.][0-9]+)*")){
                JOptionPane.showMessageDialog(null, "Please enter a valid number in Quantity Field");
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void unitOptionsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_unitOptionsPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_unitOptionsPropertyChange

    private void unitOptionsItemStateChanged(java.awt.event.ItemEvent evt) {                                             
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED) {
            System.out.println(unitOptions.getSelectedItem());
            if(unitOptions.getSelectedItem().equals("pcs") ) {
                
            }
            else if(unitOptions.getSelectedItem().equals("kg") ) {
                //double quantity = Double.parseDouble(quantityField.getText());
                //quantity /= 1000;
                //quantityField.setText(quantity + "");
                double price = Double.parseDouble(priceField.getText());
                price *= 1000;
                priceField.setText(price + "");
                double cost = Double.parseDouble(costField.getText());
                cost *= 1000;
                costField.setText(cost + "");
            }
            else {
                //double quantity = Double.parseDouble(quantityField.getText());
                //quantity *= 1000;
                //quantityField.setText(quantity + "");
                double price = Double.parseDouble(priceField.getText());
                price /= 1000;
                priceField.setText(price + "");
                double cost = Double.parseDouble(costField.getText());
                cost /= 1000;
                costField.setText(cost + "");
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductsUpdate().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField costField;
    private javax.swing.JLabel costLabel;
    private javax.swing.JLabel designeddeveloped;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JLabel mainmenubox;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel unitLabel;
    private javax.swing.JComboBox unitOptions;
    // End of variables declaration//GEN-END:variables

    private void showRecord(String name) {
        try{
            ResultSet result=DBManager.getSearchedProductRecord(name);
            while(result.next()){
                this.nameField.setText(result.getString("name"));
                this.costField.setText(result.getString("cost"));
                this.priceField.setText(result.getString("price"));
                if(result.getString("unit").equals("kg"))
                    this.quantityField.setText((result.getDouble("quantity")/1000) + "");
                else
                    this.quantityField.setText(result.getString("quantity"));
                //this.unitOptions.setText(result.getString("unit"));
                this.unitOptions.setSelectedItem(result.getString("unit"));
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        unitOptions.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                unitOptionsItemStateChanged(evt);
            }
        });
    }
}
